---
- name: Déploiement d'une page HTML sur le conteneur
  hosts: webserver
  become: true

  tasks:
    - name: Installer nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copier la page HTML
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: S'assurer que nginx est démarré
      service:
        name: nginx
        state: started
        enabled: true
